version: "3"
services:
  api:
    build: ./server/
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    healthcheck:
      test: "exit 0"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: java
      MYSQL_DATABASE: java_gym
volumes:
  db_data:
